#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
INIT_DIR=/etc/init.d
INIT_DIR_BAK=/etc/init.d.nemkell
VOLI_SERVICE_DIR=/etc/voli/init
SYSTEMD_DIR=/etc/systemd/system
###BEALLITO=				## A hívó script itt tartja ennek a file-nak az elérhetőségét
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::
#:::::: functions :::::::::::::
Remove_initd(){				## $@: Lista; A SYSV indítók eltávolítása mert: van systemd-s vagy mert nem kell
    echo "A régi indító scriptek eltávolítása....."
    [ -d ${INIT_DIR_BAK} ] || mkdir -p ${INIT_DIR_BAK}
    while [ -n "$1" ] ; do
	[   -e "${INIT_DIR}/$1"     ] &&  mv "${INIT_DIR}/$1" "${INIT_DIR_BAK}/"
	[   -e "${INIT_DIR_BAK}/$1" ] && echo "A(z) $1: 	sikeresen átmozgatva."
	[ ! -e "${INIT_DIR}/$1"     ] && [ ! -e "${INIT_DIR_BAK}/$1" ] && echo "A(z) $1: 	NEM találtam."
	shift
    done
}

Sajat_Add(){				## $@: Lista; Beállítja és telepíti ha a sajátunk
    while [ -n "$1" ]; do
	Nev=$1; shift
	if [ ! -e $VOLI_SERVICE_DIR/$Nev ]; then echo NINCS: $sv ; return; fi			## Ha nem az enyém akkor semmi
	systemctl cat $Nev >/dev/null 2>&1 							## Ha telepítve volt, akkor deaktiválom
	[ $? -eq 0 ] && systemctl disable $Nev
	[ -e $SYSTEMD_DIR/$Nev ] && rm $SYSTEMD_DIR/$Nev 					## és eltávolítom
	ln $VOLI_SERVICE_DIR/$Nev $SYSTEMD_DIR/$Nev 						## Telepítem
	[ -e $SYSTEMD_DIR/$Nev ] && echo "Telepítve: $Nev"
	systemctl cat $Nev 2>&1 |grep --silent -e "\[Install\]" 				## és Installálom ha kell
	[ $? -eq 0 ] && systemctl enable $Nev
    done
    systemctl daemon-reload
}
Sajatok_Add_kivetelekkel(){		## $@: Lista; Minden sajátot telepít kivéve a $@
    echo "------------ A sajátok telepítése:"
    ls $VOLI_SERVICE_DIR/*.service|while read sv; do
	Add_Sajat $( basename $sv )
    done
    echo "------------ Ami nem kell azt leszedem:"
    while [ -n "$1" ]; do
	if [ ! -e $VOLI_SERVICE_DIR/$1 ]; then echo "NINCS: $1"; shift; continue; fi 		## Csak az enyémekkel foglalkozom
	[   -e $SYSTEMD_DIR/$1 ] && systemctl disable $1 					## Deaktiválom és törlöm
	[   -e $SYSTEMD_DIR/$1 ] && rm $SYSTEMD_DIR/$1
	[ ! -e $SYSTEMD_DIR/$1 ] && echo "		Eltávolítva: $1"
	shift
    done
    systemctl daemon-reload
}

Service_NoAuto(){			## Autómatikusan nem indulnak el
    echo "------------ Letiltás:"
    while [ -n "$1" ]; do
	systemctl disable "$1"
	echo -n "$1: 	" ; systemctl is-enabled "$1"
	shift
    done
    systemctl daemon-reload
}
Service_Nevesit(){			## Nevesített servicet hoz létre formája. xxx@yyy.service
    echo "------------ Nevesítés:"
    while [ -n "$1" ]; do
	systemctl enable "$1"
	echo -n "$1: 	" ; systemctl is-enabled "$1"
	shift
    done
    systemctl daemon-reload
}

#:::::::: Start :::::::::::::::
    cat $BEALLITO |grep "()" |grep -v "BEALLITO" |sed 's/{//'
