#!/bin/bash
# Short-Description:	Alap beállítások
# Description:		Indulás után a RAID szinkronizalas sebességet max.-ra
#			CPU managment-et performace-ra állítja


# Author: Volarics István <volaricsi@freemail.hu>
#	Create by Voli

	CPU_SPEED=ondemand			#CPU sebesség/power/orajel állítás módja

    echo -n "Lehetseges CPU sebesség állítási módok: "
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors

    i=0
    ls /sys/devices/system/cpu/*/cpufreq/scaling_governor |while read a; do
	echo ${CPU_SPEED}>>${a}
        echo -n "A ${i}. CPU sebessege: "; cat ${a}
	i=$[ $i+1 ]
    done

echo MythTV cache torles...
rm -rf /home/mythtv/.mythtv/cache /home/mythtv/.cache


    for dev in $( ls /dev/sd[a-x] ) ; do
#	echo $dev
#hdparm -B 254 -S 0 	$dev
hdparm -B  -S 255 	$dev 	>/dev/null
idle3ctl  -d 		$dev 	>/dev/null


    done
