#!/bin/bash
# Short-Description:	Alap beállítások
# Description:		Indulás után a RAID szinkronizalas sebességet max.-ra
#			CPU managment-et performace-ra állítja


# Author: Volarics István <volaricsi@freemail.hu>
#	Create by Voli

	RAID_Speed=20000000			#RAID szinkronizáció max sebessége
	CPU_SPEED=ondemand			#CPU sebesség/power/orajel állítás módja

    echo -n "Lehetseges CPU sebesség állítási módok: "
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors

    i=0
    ls /sys/devices/system/cpu/*/cpufreq/scaling_governor |while read a; do
	echo ${CPU_SPEED}>>${a}
        echo -n "A ${i}. CPU sebessege: "; cat ${a}
	i=$[ $i+1 ]
    done

    echo ${RAID_Speed} >>/proc/sys/dev/raid/speed_limit_min
    echo ${RAID_Speed} >>/proc/sys/dev/raid/speed_limit_max
    echo -n "RAID: speed_limit_min: "; cat /proc/sys/dev/raid/speed_limit_min
    echo -n "RAID: speed_limit_max: "; cat /proc/sys/dev/raid/speed_limit_max

echo MythTV cache torles...
rm -rf /home/mythtv/.mythtv/cache /home/mythtv/.cache
