#!/bin/bash
#	Created by Volarics Istvan (Voli)
#Ha 1 óránál régebbi adat van az idokep.hu-n akkor már jön is az üzenet.
#NE futtasd 5 percenként sűrűbben mert kell idő az első kiolvasáshoz és felküldéshez....

#:::::: Fix beallitasok :::::::
	. /etc/voli-env/idokep.env

#:::::: Beallitasok :::::::::::
	URL="https://www.idokep.hu/automata/${IDOKEP_AUTOMATA_NEV}"
	SOR="Utolsó mérés"
#:::::: Fuggvenyek ::::::::::::
#:::::::: Start :::::::::::::::
	IdokepSor=$( curl --silent ${URL} |grep "${SOR}" )

	if [ ".${IdokepSor}" == "." ]; then 
	    echo "Rossz vagy nincs válasz..."
	    exit;
	fi
exit 0
	Most=$( date "+%k*60+%M" )
	Feltoltve=$( echo "${IdokepSor}"|sed "s/.*${SOR}//g; s/.*<b>//g; s/<\/b>.*//g; s/.* //g; s/:/*60+/g; s/^0//g; " )

#Most=29*60+2 	#Tesztre

	Diff=$[ (${Most}) - (${Feltoltve}) ]

	[ ${Diff} -le ${IDO_ELTERES_MAX} ] && exit 0

	echo "---Idő:${Most}	Feltöltve:${Feltoltve}	Differencia:${Diff}/	Túl nagy az idő külömbség..."
	echo ${IdokepSor}


