#!/bin/bash
#
# Időkép automata adatgyüjtés és mentés .by VolaricsI
#
#:::::: Fix beallitasok :::::::
HOST="idokep_automata"
USER=idokep
DIR_SAVE=/var/lib/idokep/Idokep_
MARAD=10

#:::::: Beallitasok :::::::::::
URL="http://${HOST}/cgi-bin/luci/admin/status/automata/"
TMP_FILE=/tmp/$( basename $0 )_$$
SAVE_KIT=.sql.gz
FileNeve=${DIR_SAVE}$( date "+%Y-%m-%d_%H.%M.%S" )${SAVE_KIT}
FileNeve=${DIR_SAVE}$( date "+%Y-%m-%d_%H.%M" )${SAVE_KIT}

#:::::: Fuggvenyek ::::::::::::
Mentes(){
    mysqldump --user=${USER} --databases idokep | gzip >${FileNeve}

    Meret_most=$( wc -c <${FileNeve} )
    while : ; do
	cnt=$( ls ${DIR_SAVE}*${SAVE_KIT} |grep -c "." )
	[  ${cnt} -gt ${MARAD} ] || break			##Csak $MARAD db kerül tárolásra

	ls ${DIR_SAVE}*${SAVE_KIT}|sort|while read fname; do
	    Meret=$( wc -c <${fname} )
	    [ ${Meret} -gt ${Meret_most} ] && continue		##A nagyobb méretüeket nem törlöm
	    rm "${fname}"
	    break
	done
    done
}

#:::::: Start :::::::::::::::::
if [ ".$1" == ".mentes" ]; then
	Mentes
	exit 0
fi

	wget -t 1 -T 5 -nv -o /dev/null -O "${TMP_FILE}"  "${URL}"
	if [ $? -ne 0 ]; then rm "${TMP_FILE}"; exit 1; fi

	cat "${TMP_FILE}" 	|sgrep '"<h2>WS23XX m&eacute;rt adatai</h2> " .. "<h2>TE923/TE823 m&eacute;rt adatai</h2>"' |grep -v -e "^<.*> *$" -e "^$"|sed 's/<pre>//g; '  	>${TMP_FILE}1
	mv ${TMP_FILE}1 ${TMP_FILE}

	Csapadek_1h=NULL; Csapadek_24h=NULL	#???????????????????????

	while read -r line; do
		line=${line//,/_}		##Vessző nem lehet az eval miatt
		eval $line
	done < ${TMP_FILE}
	rm ${TMP_FILE}
	[ -z ${Relativ_paratartalom} ] || [ ${Relativ_paratartalom} -gt 100   ] && Relativ_paratartalom=NULL
	[ ".${Kulso_homerseklet}" = ".81.0" ] && Kulso_homerseklet=NULL



	SQL="USE idokep; "
	SQL="${SQL} INSERT INTO adat (   Belso_homerseklet,    Belso_paratartalom,    Kulso_homerseklet,    Relativ_paratartalom,    Abszolut_legnyomas,    Relativ_legnyomas,    Csapadek_1h,    Csapadek_24h ) "
	SQL="${SQL} VALUES           ( ${Belso_homerseklet}, ${Belso_paratartalom}, ${Kulso_homerseklet}, ${Relativ_paratartalom}, ${Abszolut_legnyomas}, ${Relativ_legnyomas}, ${Csapadek_1h}, ${Csapadek_24h} ); "
##	echo ${SQL}

	mysql -u "${USER}" -e "${SQL}"
