#!/bin/bash
#
# Időkép automata adatgyüjtés és mentés .by VolaricsI
#
#:::::: Fix beallitasok :::::::
. /etc/voli/idokep.env

#:::::: Beallitasok :::::::::::
URL="http://${HOST}/cgi-bin/luci/admin/status/automata/"
TMP_FILE=/tmp/$( basename $0 )_$$
SAVE_KIT=.sql.gz
FileNeve=${SAVE_DIR}${SAVE_FILE_ELOTAG}$( date "+%Y-%m-%d_%H.%M.%S" )${SAVE_KIT}

#:::::: Fuggvenyek ::::::::::::
Mentes(){
    mysqldump --user=${USER} --databases idokep | gzip >${FileNeve}
    Meret_most=$( wc -c <${FileNeve} )
    while : ; do
	cnt=$( ls ${SAVE_DIR}${SAVE_FILE_ELOTAG}*${SAVE_KIT} |grep -c "." )
	[  ${cnt} -gt ${MARAD} ] || break			##Csak $MARAD db kerül tárolásra

	ls ${SAVE_DIR}*${SAVE_KIT}|sort|while read fname; do
	    Meret=$( wc -c <${fname} )
	    [ ${Meret} -gt ${Meret_most} ] && continue		##A nagyobb méretüeket nem törlöm
	    rm "${fname}"
	    break
	done
    done
}

#:::::: Start :::::::::::::::::
if [ ".$1" == ".mentes" ]; then
	Mentes
	exit 0
fi

	curl --silent "${URL}" >"${TMP_FILE}"
	if [ $? -ne 0 ]; then rm "${TMP_FILE}"; exit 1; fi

	cat "${TMP_FILE}" 	|sgrep '"<h2>WS23XX m&eacute;rt adatai</h2> " .. "<h2>TE923/TE823 m&eacute;rt adatai</h2>"' |grep -v -e "^<.*> *$" -e "^$"|sed 's/<pre>//g; '  	>${TMP_FILE}1
	mv ${TMP_FILE}1 ${TMP_FILE}

	Csapadek_1h=NULL; Csapadek_24h=NULL	#???????????????????????

	while read -r line; do
		line=${line//,/_}		##Vessző nem lehet az eval miatt
		eval $line
	done < ${TMP_FILE}
	rm ${TMP_FILE}
	[ -z ${Relativ_paratartalom} ] || [ ${Relativ_paratartalom} -gt 100   ] && Relativ_paratartalom=NULL
	[ ".${Kulso_homerseklet}" = ".81.0" ] && Kulso_homerseklet=NULL 					##Mert nem egész, ezért kell string-ként kezelni

	SQL="USE idokep; "
	SQL="${SQL} INSERT INTO adat (   Belso_homerseklet,    Belso_paratartalom,    Kulso_homerseklet,    Relativ_paratartalom,    Abszolut_legnyomas,    Relativ_legnyomas,    Csapadek_1h,    Csapadek_24h ) "
	SQL="${SQL} VALUES           ( ${Belso_homerseklet}, ${Belso_paratartalom}, ${Kulso_homerseklet}, ${Relativ_paratartalom}, ${Abszolut_legnyomas}, ${Relativ_legnyomas}, ${Csapadek_1h}, ${Csapadek_24h} ); "

	mysql -u "${USER}" -e "${SQL}"
