#!/bin/bash
# Author: Volarics István <volaricsi@freemail.hu>
#	Create by Voli

#:::::: Fix beallitasok :::::::
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::

swapoff -a ; swapon  -a

sync --file-system


case $( date +%H ) in

	02,05,08,11,14,17,20,23)
		echo 2 >/proc/sys/vm/drop_caches
	;;

	00,03,06,09,12,15,18,21 )
		echo 3 >/proc/sys/vm/drop_caches
	;;

esac
