#!/bin/bash
#	Created by Volarics Istvan (Voli)

#:::::: Fix beallitasok :::::::
TAROLO="/var/lib/voli"
KIVETELEK=/etc/voli/smart_kivetelek
#:::::: Beallitasok :::::::::::
Referencia=${TAROLO}/Alap_
HDDK=$( ls /dev/sd[a-x] /dev/nvme[0-9]n[0-9] |sed 's/.*\///g;' |sort) 	#Ezekről készít
#:::::: Fuggvenyek ::::::::::::
AlapErtekFelvetel(){
	[ -d ${TAROLO} ] || mkdir -p ${TAROLO}
	for a in ${HDDK} ; do
		if [ ! -b /dev/${a} ]; then continue; fi
		echo $a
		smartctl --all "/dev/${a}"	>${Referencia}${a}
		if [ "$?" != "0" ]; then
			smartctl --all "/dev/${a}"
			echo "Visszatérési érték hiba: $?"
		fi
	done
}

Start(){
		## Referencia idejét jó tudni!!
	RefTime=$(  grep -e "Local Time is:" "${Referencia}sda" 	|sed 's/.*: //g; s/^ \+//g; ' )
	date --date="$RefTime" "+=================> A referencia ideje: %Y.%m.%d. <================="

	for a in ${HDDK} ; do
		smartctl --all "/dev/${a}" >"${TAROLO}/${a}" ; SmartExitCode=$?

		ModelNev=$( grep -e "^Device Model:" -e "^Model Number:" "${TAROLO}/${a}" |sed 's/.*: //g; s/^ \+//g; ' )
		echo "------------------ ${a} --> ${ModelNev} 	------------------"

		if [ $SmartExitCode -ne 0 ]; then
		    echo "SmartExitCode: $SmartExitCode."
		fi

		diff "${Referencia}${a}" "${TAROLO}/${a}" |grep -v -f "${KIVETELEK}"
	done
}


#:::::::: Start :::::::::::::::
case "$1" in
	alap)
		AlapErtekFelvetel
	;;
	*)
		Start
	;;
esac
exit 0
