#!/bin/bash
#	Created by Volarics Istvan (Voli)

#:::::: Fix beallitasok :::::::
TAROLO="/var/lib/voli"
KIVETELEK=/etc/voli/smart_kivetelek
#:::::: Beallitasok :::::::::::
Referencia=${TAROLO}/Alap_
ReferenciaLista=$( ls ${Referencia}* |sort )
HDDK=$( ls /dev/sd[a-x] /dev/nvme[0-9]n[0-9]  2>/dev/null |sed 's/.*\///g;' |sort) 	#Ezekről készít
#:::::: Fuggvenyek ::::::::::::
AlapErtekFelvetel(){
	[ -d ${TAROLO} ] || mkdir -p ${TAROLO}
	if [ ".$1" != "." ]; then HDDK=$1; fi				## Ha csak bizonyos hdd(k)-(e)t akarsz frissíteni
	for a in ${HDDK} ; do
		if [ ! -b /dev/${a} ]; then continue; fi
		echo $a
		smartctl --all "/dev/${a}"	>${Referencia}${a}
		Ret=$?
		Serial=$( grep -e "^Serial Number:" ${Referencia}${a} |sed 's/.*: \+//g ' )
		mv ${Referencia}${a} ${Referencia}${Serial}

		[ "$Ret" -eq 0 ] && continue
		    cat ${Referencia}${Serial}
		    echo "Visszatérési érték hiba: $Ret"
	done
}

ResultList(){
	val=$1; mask=1
	for i in 0 1 2 3 4 5 6 7; do
	    echo "Bit $i: $(((val & mask) && 1))"
	    mask=$((mask << 1))
	done
}

Result(){
	for a in ${HDDK} ; do
		[ ! -b /dev/${a} ] && continue
		echo $a
		Result=$( smartctl --all "/dev/${a}" ); Ret=$?; 			# Így kell mert a smart resultja kell és nem a grep-é
		[ $Ret -eq 0 ] && continue
		echo "${Result}" |grep -e "Model Family:" -e "Device Model:" -e "^#" -e "Model Number:" -e "Serial Number:"
		echo "Visszatérési érték: $Ret"
		ResultList ${Ret}
	done
}

Start(){
		## Referencia idejét jó tudni!!
	for b in $ReferenciaLista ; do
	    RefTime=$(  grep -e "Local Time is:" "${b}" 	|sed 's/.*: \+//g ' )
	    date --date="$RefTime" "+=================> A referencia ideje: %Y.%m.%d. <================="
	    break
	done

	for a in ${HDDK} ; do
		smartctl --all "/dev/${a}" >"${TAROLO}/${a}" ; SmartExitCode=$?

		ModelNev=$( grep -e "^Device Model:" -e "^Model Number:" "${TAROLO}/${a}" |sed 's/.*: \+//g ' )
		Serial=$(   grep -e "^Serial Number:"                    "${TAROLO}/${a}" |sed 's/.*: \+//g ' )
		echo "------------------ ${a} --> ${ModelNev} ==> ${Serial} 	------------------"

		for b in $ReferenciaLista ; do
		    grep -c -e "$Serial" "${b}" >/dev/null
		    [ $? -ne 0 ] && continue
			diff "${b}" "${TAROLO}/${a}" |grep -v -f "${KIVETELEK}" -e "^[0-9a-f,]\+$"
			break
		done
		[ $SmartExitCode -ne 0 ] && echo "SmartExitCode: $SmartExitCode."
	done
}


#:::::::: Start :::::::::::::::
case "$1" in
	alap)
		AlapErtekFelvetel $2
	;;
	teszt)
		Result
	;;
	*)
		Start
	;;
esac
exit 0
