#!/bin/bash
# Author: Volarics István <volaricsi@freemail.hu>
#	Create by Voli

#:::::: Fix beallitasok :::::::
VPN_STATUS_FILE=/etc/openvpn/1_munin-srv.status 	#	Ez verzio 3-asra készült

#:::::: Beallitasok :::::::::::
MUNIN_DIR=/etc/munin/munin-conf.d
S_routeing="CLIENT_LIST"
S_munin=address
#:::::: Ellenorzesek ::::::::::
cat ${VPN_STATUS_FILE} |grep "^CLIENT_LIST" |cut -d$'\t' -f 2,4 |while read a; do
    Nev=$( echo "$a"|cut -d$'\t' -f 1 )

    Ip_Current=$( echo "$a"|cut -d$'\t' -f 2  )
    Ip_munin=$( [ -r "${MUNIN_DIR}/${Nev}.conf" ] && grep -e "${S_munin}" "${MUNIN_DIR}/${Nev}.conf" |sed "s/.*${S_munin}//g; s/[ \t]\+//g; " )


    if [ "${Ip_Current}" = "${Ip_munin}" ] ; then
	continue;
    fi

    echo "A VPN-ben hasznalt nev: ${Nev}."
    echo "Az aktualis IP: 	${Ip_Current}"
    echo "A munin-ban IP: 	${Ip_munin}"
    echo
done
